import Head from '../../node_modules/next/head'
import ImgLogin from '../assets/login.svg'
import {
    Container,
    Button,
    Form,
    Section,
    DivInput,
    ButtonSignUp
} from '../styles/pages/login'

const Login = () => {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="https://cdn-icons-png.flaticon.com/512/3959/3959542.png"
                />
            </Head>
            <Container>
                <ImgLogin />
                <Section>
                    <Form action="">
                        <DivInput>
                            <label>Email</label>
                            <input type="text" />
                        </DivInput>
                        <DivInput>
                            <label>Password</label>
                            <input type="text" />
                        </DivInput>
                        <Button>Logar</Button>
                        <span>
                            Não possui conta ainda ?
                            <ButtonSignUp>Cadastre-se</ButtonSignUp>
                        </span>
                    </Form>
                </Section>
            </Container>
        </>
    )
}

export default Login
