import Head from '../../node_modules/next/head'
import { useRouter } from '../../node_modules/next/router'
import ImgSignUp from '../assets/signup.svg'
import { Container, Section, DivInput, Form, Button, ButtonLogin } from '../styles/pages/signup'

const SignUp = () => {
    const router = useRouter()

    const changePage = (path: string) => {
        router.push(path)
    }

    return (
        <>
            <Head>
                <title>Sign Up</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="https://cdn-icons-png.flaticon.com/512/3959/3959542.png"
                />
            </Head>
            <Container>
                <ImgSignUp />
                <Section>
                    <Form action="">
                        <DivInput>
                            <label>Username</label>
                            <input type="text" />
                        </DivInput>
                        <DivInput>
                            <label>Email</label>
                            <input type="text" />
                        </DivInput>
                        <DivInput>
                            <label>Avatar URL</label>
                            <input type="text" />
                        </DivInput>
                        <DivInput>
                            <label>Password</label>
                            <input type="text" />
                        </DivInput>
                        <Button onClick={() => changePage('/')}>Sign Up</Button>
                        <span>
                            Já possui conta ainda ?
                            <ButtonLogin onClick={() => changePage('/')} type='button'>Logar</ButtonLogin>
                        </span>
                    </Form>
                </Section>
            </Container>
        </>
    )
}

export default SignUp
